#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
PROJECT="cadre-ai-challenge"
ACCOUNT="galo.s.becerra@gmail.com"

# Run from the repo root so ENV_FILE=.env resolves.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# ok "msg" / bad "msg": verification results.
ok()  { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# _json_get FIELD: read one top-level field from JSON on stdin ("" if absent).
_json_get() { python3 -c 'import sys,json
try: d=json.load(sys.stdin)
except Exception: d={}
v=d
for k in sys.argv[1].split("."):
    v=v.get(k) if isinstance(v,dict) else None
print("" if v is None else v)' "$1"; }

# _push_secret NAME VALUE: create the Secret Manager secret, or add a version
# only when the value changed. Never prints the value.
_push_secret() {
  local name="$1" value="$2" current
  if gcloud secrets describe "$name" --project "$PROJECT" >/dev/null 2>&1; then
    current=$(gcloud secrets versions access latest --secret "$name" --project "$PROJECT" 2>/dev/null || true)
    if [[ "$current" == "$value" ]]; then ok "$name unchanged in Secret Manager"; return; fi
    printf '%s' "$value" | gcloud secrets versions add "$name" --project "$PROJECT" --data-file=- >/dev/null \
      && ok "$name: new version added" || { bad "$name: could not add version"; SKIPPED+=("Secret Manager: $name"); }
  else
    printf '%s' "$value" | gcloud secrets create "$name" --project "$PROJECT" --replication-policy=automatic --data-file=- >/dev/null \
      && ok "$name created in Secret Manager" || { bad "$name: could not create"; SKIPPED+=("Secret Manager: $name"); }
  fi
}

banner "Cadre support agent · credentials & GCP setup"

# ── Stage 1: Application Default Credentials ─────────────────────────────
stage "Google Cloud: Application Default Credentials"
say "Local code (Firestore, Secret Manager) authenticates with ADC. The current ADC"
say "file belongs to another Google account, so it must be re-issued for ${ACCOUNT}."
step "A browser tab will open: sign in as ${ACCOUNT} and allow access."
pause "Press Enter to open the sign-in flow"
gcloud auth application-default login --quiet >/dev/null 2>&1 || warn "login did not complete; re-run this stage later"
if gcloud auth application-default set-quota-project "$PROJECT" >/dev/null 2>&1; then
  ok "ADC quota project set to ${PROJECT}"
else
  bad "could not set the quota project — is ADC signed in as ${ACCOUNT}?"
  SKIPPED+=("gcloud auth application-default login (as ${ACCOUNT}) + set-quota-project ${PROJECT}")
fi
write_env GOOGLE_APPLICATION_CREDENTIALS ""   # empty on purpose: ADC, not a key file
pause

# ── Stage 2: Firebase Auth → Google sign-in ───────────────────────────────
stage "Firebase Auth: enable Google sign-in (Console login)"
say "The Strategist console signs in with Google; only ADMIN_ALLOWED_EMAILS get in."
open_url "https://console.firebase.google.com/project/${PROJECT}/authentication/providers"
step "If you see 'Get started', click it."
step "Add new provider → Google → toggle Enable."
step "Project support email: ${ACCOUNT} → Save."
note "Authorized domains: localhost is pre-authorized; the Cloud Run *.run.app host is added after the first deploy."
pause "Press Enter once Google shows as Enabled"
_token=$(gcloud auth print-access-token 2>/dev/null || true)
_google=$(curl -sS --max-time 15 \
  "https://identitytoolkit.googleapis.com/admin/v2/projects/${PROJECT}/defaultSupportedIdpConfigs/google.com" \
  -H "Authorization: Bearer ${_token}" -H "x-goog-user-project: ${PROJECT}" | _json_get enabled || true)
if [[ "$_google" == "True" ]]; then ok "google.com provider is enabled"; else
  bad "google.com provider not reported as enabled yet"; SKIPPED+=("Enable Google sign-in in Firebase Auth")
fi
pause

# ── Stage 3: OpenRouter ───────────────────────────────────────────────────
stage "OpenRouter: the API key"
say "OpenRouter is the only LLM provider; the key (yours, or the one Cadre issued) is verified, never echoed."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter key (sk-or-…):"
_key=$(curl -sS --max-time 15 https://openrouter.ai/api/v1/key -H "Authorization: Bearer ${OPENROUTER_API_KEY}" || true)
_label=$(printf '%s' "$_key" | _json_get data.label); _left=$(printf '%s' "$_key" | _json_get data.limit_remaining)
if [[ -n "$_label" || -n "$_left" ]]; then ok "key valid · label: ${_label:-—} · credit remaining: ${_left:-unlimited}"; else
  bad "OpenRouter rejected the key: $(printf '%s' "$_key" | _json_get error.message)"; SKIPPED+=("Valid OPENROUTER_API_KEY")
fi
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
pause

# ── Stage 4: Langfuse ─────────────────────────────────────────────────────
stage "Langfuse: project API keys"
say "Traces, cost per conversation, feedback scores and eval datasets all land here."
open_url "https://cloud.langfuse.com"
step "Create or open the project (e.g. 'cadre-support-agent') → Settings → API Keys → Create."
step "Note the region: EU keys use https://cloud.langfuse.com, US keys use https://us.cloud.langfuse.com."
ask LANGFUSE_HOST "Langfuse host:"
ask LANGFUSE_PUBLIC_KEY "Public key (pk-lf-…):"
ask_secret LANGFUSE_SECRET_KEY "Secret key (sk-lf-…):"
_proj=$(curl -sS --max-time 15 -u "${LANGFUSE_PUBLIC_KEY}:${LANGFUSE_SECRET_KEY}" "${LANGFUSE_HOST%/}/api/public/projects" | python3 -c 'import sys,json
try: d=json.load(sys.stdin)
except Exception: d={}
print(", ".join(p.get("name","?") for p in d.get("data",[])))' || true)
if [[ -n "$_proj" ]]; then ok "keys valid · project: ${_proj}"; else
  bad "Langfuse rejected the keys (check host/region)"; SKIPPED+=("Valid Langfuse keys + host")
fi
write_env LANGFUSE_HOST "$LANGFUSE_HOST"
write_env LANGFUSE_PUBLIC_KEY "$LANGFUSE_PUBLIC_KEY"
write_env LANGFUSE_SECRET_KEY "$LANGFUSE_SECRET_KEY"
pause

# ── Stage 5: Daily.co ─────────────────────────────────────────────────────
stage "Daily.co: video for Live Hand-over"
say "Rooms are created per handover request via the REST API; the domain comes back from the API."
open_url "https://dashboard.daily.co/developers"
step "Copy the API key from the Developers page (create one if none)."
ask_secret DAILY_API_KEY "Paste the Daily API key:"
_domain=$(curl -sS --max-time 15 https://api.daily.co/v1/ -H "Authorization: Bearer ${DAILY_API_KEY}" | _json_get domain_name || true)
if [[ -n "$_domain" ]]; then
  ok "key valid · domain: ${_domain}.daily.co"
  DAILY_DOMAIN="${_domain}.daily.co"
else
  bad "Daily rejected the key"; SKIPPED+=("Valid DAILY_API_KEY")
  ask DAILY_DOMAIN "Daily domain (e.g. cadre-demo.daily.co):"
fi
write_env DAILY_API_KEY "$DAILY_API_KEY"
write_env DAILY_DOMAIN "$DAILY_DOMAIN"
pause

# ── Stage 6: Secret Manager for Cloud Run ─────────────────────────────────
stage "Secret Manager: what Cloud Run and Functions read at runtime"
say "The deployed services never read .env; they mount these four secrets."
note "CI needs no secrets at all: unit tests and the stub-provider evals run without any provider."
if confirm "Push/refresh openrouter-api-key, langfuse-secret-key, langfuse-public-key, daily-api-key in ${PROJECT}?"; then
  _push_secret openrouter-api-key   "$OPENROUTER_API_KEY"
  _push_secret langfuse-secret-key  "$LANGFUSE_SECRET_KEY"
  _push_secret langfuse-public-key  "$LANGFUSE_PUBLIC_KEY"
  _push_secret daily-api-key        "$DAILY_API_KEY"
else
  SKIPPED+=("Secret Manager push (re-run: scripts/setup-wizard.sh)")
fi
pause
# ──────────────────────────────────────────────────────────────────────────

finish
