#!/usr/bin/env bash
#
# tickets-to-tasks.sh — generate the subagent-driven-development (SDD) adapter
# file from the local issue tracker.
#
# SDD's scripts (sdd-workspace, task-brief, review-package) expect ONE plan file
# with "# Task N" headings and a "## Global Constraints" section. The tracker
# convention (docs/agents/issue-tracker.md) is one file per ticket. This script
# bridges the two: it emits tasks.md with one "# Task N" section per ticket,
# each carrying the ticket body plus the Global Constraints, so a task brief is
# self-contained. Regenerate whenever a ticket changes; commit both.
#
# Usage: scripts/tickets-to-tasks.sh [feature-slug]   (default: cadre-support-agent)

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

SLUG="${1:-cadre-support-agent}"
DIR=".scratch/${SLUG}"
OUT="${DIR}/tasks.md"
CONSTRAINTS="${DIR}/global-constraints.md"

[ -d "${DIR}/issues" ] || { echo "no tickets at ${DIR}/issues" >&2; exit 1; }
[ -f "${CONSTRAINTS}" ] || { echo "missing ${CONSTRAINTS}" >&2; exit 1; }

{
  printf '# Tasks — SDD adapter for %s\n\n' "${SLUG}"
  printf 'Generated by scripts/tickets-to-tasks.sh from %s/issues/. Do not edit by hand: edit the ticket, then regenerate.\n\n' "${DIR}"
  printf 'Spec: %s/spec.md · Vocabulary: CONTEXT.md · Decisions: docs/adr/ · Diagrams: docs/architecture.md · Plan: plan.md\n\n' "${DIR}"
  printf 'Work the frontier: a task may start when every ticket in its "Blocked by" line is done. One ticket = one branch = one PR.\n\n'
  cat "${CONSTRAINTS}"
  for f in "${DIR}"/issues/[0-9][0-9]-*.md; do
    num=$(basename "${f}" | cut -c1-2)
    n=$((10#${num}))
    title=$(sed -n '1s/^# [0-9][0-9]*: //p' "${f}")
    printf '\n# Task %d: %s\n\n' "${n}" "${title}"
    printf 'Source ticket: `%s` — read it first; it is your requirements. Then read the spec'"'"'s Testing Decisions, CONTEXT.md, and the ADRs this area touches.\n\n' "${f}"
    tail -n +2 "${f}"
    printf '\n'
    cat "${CONSTRAINTS}"
  done
} > "${OUT}"

count=$(grep -c '^# Task ' "${OUT}")
echo "wrote ${OUT}: ${count} tasks"
